version: "3"

services:
  web:
    build: .
    command: bash -c "python vktestapi/manage.py makemigrations && python vktestapi/manage.py migrate --run-syncdb && python vktestapi/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"